-- =============================================================================
-- SEED: stickers_catalog
-- Genera los INSERT para Panini y 3 Reyes.
-- Ejecutar DESPUÉS de schema.sql.
-- Este archivo fue generado a partir de src/data/panini.json y treyes.json.
-- =============================================================================

-- Para regenerarlo desde los JSON, ejecutar:
--   node supabase/generate_seed.mjs > supabase/seed_stickers.sql

do $$
declare
  v_panini_id uuid;
  v_treyes_id uuid;
begin
  select id into v_panini_id from albums_catalog where slug = 'panini-2024';
  select id into v_treyes_id from albums_catalog where slug = '3reyes-2024';

  -- ── PANINI MUNDIAL 2024 ──────────────────────────────────────────────────
  insert into stickers_catalog (album_id, number, name, section) values
    (v_panini_id,   1, 'Selecciones 1',     'Selecciones'),
    (v_panini_id,   2, 'Selecciones 2',     'Selecciones'),
    (v_panini_id,   3, 'Selecciones 3',     'Selecciones'),
    (v_panini_id,   4, 'Selecciones 4',     'Selecciones'),
    (v_panini_id,   5, 'Selecciones 5',     'Selecciones'),
    (v_panini_id,   6, 'Selecciones 6',     'Selecciones'),
    (v_panini_id,   7, 'Selecciones 7',     'Selecciones'),
    (v_panini_id,   8, 'Selecciones 8',     'Selecciones'),
    (v_panini_id,   9, 'Selecciones 9',     'Selecciones'),
    (v_panini_id,  10, 'Selecciones 10',    'Selecciones'),
    (v_panini_id,  11, 'Selecciones 11',    'Selecciones'),
    (v_panini_id,  12, 'Selecciones 12',    'Selecciones'),
    (v_panini_id,  13, 'Grupo A 1',         'Grupo A'),
    (v_panini_id,  14, 'Grupo A 2',         'Grupo A'),
    (v_panini_id,  15, 'Grupo A 3',         'Grupo A'),
    (v_panini_id,  16, 'Grupo A 4',         'Grupo A'),
    (v_panini_id,  17, 'Grupo A 5',         'Grupo A'),
    (v_panini_id,  18, 'Grupo A 6',         'Grupo A'),
    (v_panini_id,  19, 'Grupo A 7',         'Grupo A'),
    (v_panini_id,  20, 'Grupo A 8',         'Grupo A'),
    (v_panini_id,  21, 'Grupo A 9',         'Grupo A'),
    (v_panini_id,  22, 'Grupo A 10',        'Grupo A'),
    (v_panini_id,  23, 'Grupo A 11',        'Grupo A'),
    (v_panini_id,  24, 'Grupo A 12',        'Grupo A'),
    (v_panini_id,  25, 'Grupo B 1',         'Grupo B'),
    (v_panini_id,  26, 'Grupo B 2',         'Grupo B'),
    (v_panini_id,  27, 'Grupo B 3',         'Grupo B'),
    (v_panini_id,  28, 'Grupo B 4',         'Grupo B'),
    (v_panini_id,  29, 'Grupo B 5',         'Grupo B'),
    (v_panini_id,  30, 'Grupo B 6',         'Grupo B'),
    (v_panini_id,  31, 'Grupo B 7',         'Grupo B'),
    (v_panini_id,  32, 'Grupo B 8',         'Grupo B'),
    (v_panini_id,  33, 'Grupo B 9',         'Grupo B'),
    (v_panini_id,  34, 'Grupo B 10',        'Grupo B'),
    (v_panini_id,  35, 'Grupo B 11',        'Grupo B'),
    (v_panini_id,  36, 'Grupo B 12',        'Grupo B'),
    (v_panini_id,  37, 'Grupo C 1',         'Grupo C'),
    (v_panini_id,  38, 'Grupo C 2',         'Grupo C'),
    (v_panini_id,  39, 'Grupo C 3',         'Grupo C'),
    (v_panini_id,  40, 'Grupo C 4',         'Grupo C'),
    (v_panini_id,  41, 'Grupo C 5',         'Grupo C'),
    (v_panini_id,  42, 'Grupo C 6',         'Grupo C'),
    (v_panini_id,  43, 'Grupo C 7',         'Grupo C'),
    (v_panini_id,  44, 'Grupo C 8',         'Grupo C'),
    (v_panini_id,  45, 'Grupo C 9',         'Grupo C'),
    (v_panini_id,  46, 'Grupo C 10',        'Grupo C'),
    (v_panini_id,  47, 'Grupo C 11',        'Grupo C'),
    (v_panini_id,  48, 'Grupo C 12',        'Grupo C'),
    (v_panini_id,  49, 'Grupo D 1',         'Grupo D'),
    (v_panini_id,  50, 'Grupo D 2',         'Grupo D'),
    (v_panini_id,  51, 'Grupo D 3',         'Grupo D'),
    (v_panini_id,  52, 'Grupo D 4',         'Grupo D'),
    (v_panini_id,  53, 'Grupo D 5',         'Grupo D'),
    (v_panini_id,  54, 'Grupo D 6',         'Grupo D'),
    (v_panini_id,  55, 'Grupo D 7',         'Grupo D'),
    (v_panini_id,  56, 'Grupo D 8',         'Grupo D'),
    (v_panini_id,  57, 'Grupo D 9',         'Grupo D'),
    (v_panini_id,  58, 'Grupo D 10',        'Grupo D'),
    (v_panini_id,  59, 'Grupo D 11',        'Grupo D'),
    (v_panini_id,  60, 'Grupo D 12',        'Grupo D'),
    (v_panini_id,  61, 'Grupo E 1',         'Grupo E'),
    (v_panini_id,  62, 'Grupo E 2',         'Grupo E'),
    (v_panini_id,  63, 'Grupo E 3',         'Grupo E'),
    (v_panini_id,  64, 'Grupo E 4',         'Grupo E'),
    (v_panini_id,  65, 'Grupo E 5',         'Grupo E'),
    (v_panini_id,  66, 'Grupo E 6',         'Grupo E'),
    (v_panini_id,  67, 'Grupo E 7',         'Grupo E'),
    (v_panini_id,  68, 'Grupo E 8',         'Grupo E'),
    (v_panini_id,  69, 'Grupo E 9',         'Grupo E'),
    (v_panini_id,  70, 'Grupo E 10',        'Grupo E'),
    (v_panini_id,  71, 'Grupo E 11',        'Grupo E'),
    (v_panini_id,  72, 'Grupo E 12',        'Grupo E'),
    (v_panini_id,  73, 'Grupo F 1',         'Grupo F'),
    (v_panini_id,  74, 'Grupo F 2',         'Grupo F'),
    (v_panini_id,  75, 'Grupo F 3',         'Grupo F'),
    (v_panini_id,  76, 'Grupo F 4',         'Grupo F'),
    (v_panini_id,  77, 'Grupo F 5',         'Grupo F'),
    (v_panini_id,  78, 'Grupo F 6',         'Grupo F'),
    (v_panini_id,  79, 'Grupo F 7',         'Grupo F'),
    (v_panini_id,  80, 'Grupo F 8',         'Grupo F'),
    (v_panini_id,  81, 'Grupo F 9',         'Grupo F'),
    (v_panini_id,  82, 'Grupo F 10',        'Grupo F'),
    (v_panini_id,  83, 'Grupo F 11',        'Grupo F'),
    (v_panini_id,  84, 'Grupo F 12',        'Grupo F'),
    (v_panini_id,  85, 'Grupo G 1',         'Grupo G'),
    (v_panini_id,  86, 'Grupo G 2',         'Grupo G'),
    (v_panini_id,  87, 'Grupo G 3',         'Grupo G'),
    (v_panini_id,  88, 'Grupo G 4',         'Grupo G'),
    (v_panini_id,  89, 'Grupo G 5',         'Grupo G'),
    (v_panini_id,  90, 'Grupo G 6',         'Grupo G'),
    (v_panini_id,  91, 'Grupo G 7',         'Grupo G'),
    (v_panini_id,  92, 'Grupo G 8',         'Grupo G'),
    (v_panini_id,  93, 'Grupo G 9',         'Grupo G'),
    (v_panini_id,  94, 'Grupo G 10',        'Grupo G'),
    (v_panini_id,  95, 'Grupo G 11',        'Grupo G'),
    (v_panini_id,  96, 'Grupo G 12',        'Grupo G'),
    (v_panini_id,  97, 'Grupo H 1',         'Grupo H'),
    (v_panini_id,  98, 'Grupo H 2',         'Grupo H'),
    (v_panini_id,  99, 'Grupo H 3',         'Grupo H'),
    (v_panini_id, 100, 'Grupo H 4',         'Grupo H'),
    (v_panini_id, 101, 'Grupo H 5',         'Grupo H'),
    (v_panini_id, 102, 'Grupo H 6',         'Grupo H'),
    (v_panini_id, 103, 'Grupo H 7',         'Grupo H'),
    (v_panini_id, 104, 'Grupo H 8',         'Grupo H'),
    (v_panini_id, 105, 'Grupo H 9',         'Grupo H'),
    (v_panini_id, 106, 'Grupo H 10',        'Grupo H'),
    (v_panini_id, 107, 'Grupo H 11',        'Grupo H'),
    (v_panini_id, 108, 'Grupo H 12',        'Grupo H'),
    (v_panini_id, 109, 'Estrellas 1',       'Estrellas'),
    (v_panini_id, 110, 'Estrellas 2',       'Estrellas'),
    (v_panini_id, 111, 'Estrellas 3',       'Estrellas'),
    (v_panini_id, 112, 'Estrellas 4',       'Estrellas'),
    (v_panini_id, 113, 'Estrellas 5',       'Estrellas'),
    (v_panini_id, 114, 'Estrellas 6',       'Estrellas'),
    (v_panini_id, 115, 'Estrellas 7',       'Estrellas'),
    (v_panini_id, 116, 'Estrellas 8',       'Estrellas'),
    (v_panini_id, 117, 'Estrellas 9',       'Estrellas'),
    (v_panini_id, 118, 'Estrellas 10',      'Estrellas'),
    (v_panini_id, 119, 'Estrellas 11',      'Estrellas'),
    (v_panini_id, 120, 'Estrellas 12',      'Estrellas'),
    (v_panini_id, 121, 'Estrellas 13',      'Estrellas'),
    (v_panini_id, 122, 'Estrellas 14',      'Estrellas'),
    (v_panini_id, 123, 'Estrellas 15',      'Estrellas'),
    (v_panini_id, 124, 'Estadios 1',        'Estadios'),
    (v_panini_id, 125, 'Estadios 2',        'Estadios'),
    (v_panini_id, 126, 'Estadios 3',        'Estadios'),
    (v_panini_id, 127, 'Estadios 4',        'Estadios'),
    (v_panini_id, 128, 'Estadios 5',        'Estadios'),
    (v_panini_id, 129, 'Estadios 6',        'Estadios'),
    (v_panini_id, 130, 'Estadios 7',        'Estadios'),
    (v_panini_id, 131, 'Estadios 8',        'Estadios'),
    (v_panini_id, 132, 'Estadios 9',        'Estadios'),
    (v_panini_id, 133, 'Estadios 10',       'Estadios'),
    (v_panini_id, 134, 'Estadios 11',       'Estadios'),
    (v_panini_id, 135, 'Estadios 12',       'Estadios'),
    (v_panini_id, 136, 'Especiales 1',      'Especiales'),
    (v_panini_id, 137, 'Especiales 2',      'Especiales'),
    (v_panini_id, 138, 'Especiales 3',      'Especiales'),
    (v_panini_id, 139, 'Especiales 4',      'Especiales'),
    (v_panini_id, 140, 'Especiales 5',      'Especiales'),
    (v_panini_id, 141, 'Especiales 6',      'Especiales'),
    (v_panini_id, 142, 'Especiales 7',      'Especiales'),
    (v_panini_id, 143, 'Especiales 8',      'Especiales'),
    (v_panini_id, 144, 'Especiales 9',      'Especiales'),
    (v_panini_id, 145, 'Especiales 10',     'Especiales')
  on conflict (album_id, number) do nothing;

  -- ── 3 REYES LIGA ARGENTINA ───────────────────────────────────────────────
  insert into stickers_catalog (album_id, number, name, section) values
    (v_treyes_id,   1, 'Portada 1',             'Portada'),
    (v_treyes_id,   2, 'Portada 2',             'Portada'),
    (v_treyes_id,   3, 'Portada 3',             'Portada'),
    (v_treyes_id,   4, 'Portada 4',             'Portada'),
    (v_treyes_id,   5, 'Portada 5',             'Portada'),
    (v_treyes_id,   6, 'Portada 6',             'Portada'),
    (v_treyes_id,   7, 'Portada 7',             'Portada'),
    (v_treyes_id,   8, 'Portada 8',             'Portada'),
    (v_treyes_id,   9, 'Portada 9',             'Portada'),
    (v_treyes_id,  10, 'Portada 10',            'Portada'),
    (v_treyes_id,  11, 'Portada 11',            'Portada'),
    (v_treyes_id,  12, 'Portada 12',            'Portada'),
    (v_treyes_id,  13, 'Portada 13',            'Portada'),
    (v_treyes_id,  14, 'Portada 14',            'Portada'),
    (v_treyes_id,  15, 'Portada 15',            'Portada'),
    (v_treyes_id,  16, 'Equipos 1',             'Equipos'),
    (v_treyes_id,  17, 'Equipos 2',             'Equipos'),
    (v_treyes_id,  18, 'Equipos 3',             'Equipos'),
    (v_treyes_id,  19, 'Equipos 4',             'Equipos'),
    (v_treyes_id,  20, 'Equipos 5',             'Equipos'),
    (v_treyes_id,  21, 'Equipos 6',             'Equipos'),
    (v_treyes_id,  22, 'Equipos 7',             'Equipos'),
    (v_treyes_id,  23, 'Equipos 8',             'Equipos'),
    (v_treyes_id,  24, 'Equipos 9',             'Equipos'),
    (v_treyes_id,  25, 'Equipos 10',            'Equipos'),
    (v_treyes_id,  26, 'Equipos 11',            'Equipos'),
    (v_treyes_id,  27, 'Equipos 12',            'Equipos'),
    (v_treyes_id,  28, 'Equipos 13',            'Equipos'),
    (v_treyes_id,  29, 'Equipos 14',            'Equipos'),
    (v_treyes_id,  30, 'Equipos 15',            'Equipos'),
    (v_treyes_id,  31, 'Jugadores Destacados 1', 'Jugadores Destacados'),
    (v_treyes_id,  32, 'Jugadores Destacados 2', 'Jugadores Destacados'),
    (v_treyes_id,  33, 'Jugadores Destacados 3', 'Jugadores Destacados'),
    (v_treyes_id,  34, 'Jugadores Destacados 4', 'Jugadores Destacados'),
    (v_treyes_id,  35, 'Jugadores Destacados 5', 'Jugadores Destacados'),
    (v_treyes_id,  36, 'Jugadores Destacados 6', 'Jugadores Destacados'),
    (v_treyes_id,  37, 'Jugadores Destacados 7', 'Jugadores Destacados'),
    (v_treyes_id,  38, 'Jugadores Destacados 8', 'Jugadores Destacados'),
    (v_treyes_id,  39, 'Jugadores Destacados 9', 'Jugadores Destacados'),
    (v_treyes_id,  40, 'Jugadores Destacados 10','Jugadores Destacados'),
    (v_treyes_id,  41, 'Jugadores Destacados 11','Jugadores Destacados'),
    (v_treyes_id,  42, 'Jugadores Destacados 12','Jugadores Destacados'),
    (v_treyes_id,  43, 'Jugadores Destacados 13','Jugadores Destacados'),
    (v_treyes_id,  44, 'Jugadores Destacados 14','Jugadores Destacados'),
    (v_treyes_id,  45, 'Jugadores Destacados 15','Jugadores Destacados'),
    (v_treyes_id,  46, 'Jugadores Destacados 16','Jugadores Destacados'),
    (v_treyes_id,  47, 'Jugadores Destacados 17','Jugadores Destacados'),
    (v_treyes_id,  48, 'Jugadores Destacados 18','Jugadores Destacados'),
    (v_treyes_id,  49, 'Jugadores Destacados 19','Jugadores Destacados'),
    (v_treyes_id,  50, 'Jugadores Destacados 20','Jugadores Destacados'),
    (v_treyes_id,  51, 'Goles del Torneo 1',    'Goles del Torneo'),
    (v_treyes_id,  52, 'Goles del Torneo 2',    'Goles del Torneo'),
    (v_treyes_id,  53, 'Goles del Torneo 3',    'Goles del Torneo'),
    (v_treyes_id,  54, 'Goles del Torneo 4',    'Goles del Torneo'),
    (v_treyes_id,  55, 'Goles del Torneo 5',    'Goles del Torneo'),
    (v_treyes_id,  56, 'Goles del Torneo 6',    'Goles del Torneo'),
    (v_treyes_id,  57, 'Goles del Torneo 7',    'Goles del Torneo'),
    (v_treyes_id,  58, 'Goles del Torneo 8',    'Goles del Torneo'),
    (v_treyes_id,  59, 'Goles del Torneo 9',    'Goles del Torneo'),
    (v_treyes_id,  60, 'Goles del Torneo 10',   'Goles del Torneo'),
    (v_treyes_id,  61, 'Goles del Torneo 11',   'Goles del Torneo'),
    (v_treyes_id,  62, 'Goles del Torneo 12',   'Goles del Torneo'),
    (v_treyes_id,  63, 'Goles del Torneo 13',   'Goles del Torneo'),
    (v_treyes_id,  64, 'Goles del Torneo 14',   'Goles del Torneo'),
    (v_treyes_id,  65, 'Goles del Torneo 15',   'Goles del Torneo'),
    (v_treyes_id,  66, 'Arbitros 1',            'Arbitros'),
    (v_treyes_id,  67, 'Arbitros 2',            'Arbitros'),
    (v_treyes_id,  68, 'Arbitros 3',            'Arbitros'),
    (v_treyes_id,  69, 'Arbitros 4',            'Arbitros'),
    (v_treyes_id,  70, 'Arbitros 5',            'Arbitros'),
    (v_treyes_id,  71, 'Arbitros 6',            'Arbitros'),
    (v_treyes_id,  72, 'Arbitros 7',            'Arbitros'),
    (v_treyes_id,  73, 'Arbitros 8',            'Arbitros'),
    (v_treyes_id,  74, 'Arbitros 9',            'Arbitros'),
    (v_treyes_id,  75, 'Arbitros 10',           'Arbitros'),
    (v_treyes_id,  76, 'Arbitros 11',           'Arbitros'),
    (v_treyes_id,  77, 'Arbitros 12',           'Arbitros'),
    (v_treyes_id,  78, 'Arbitros 13',           'Arbitros'),
    (v_treyes_id,  79, 'Arbitros 14',           'Arbitros'),
    (v_treyes_id,  80, 'Arbitros 15',           'Arbitros'),
    (v_treyes_id,  81, 'Historia 1',            'Historia'),
    (v_treyes_id,  82, 'Historia 2',            'Historia'),
    (v_treyes_id,  83, 'Historia 3',            'Historia'),
    (v_treyes_id,  84, 'Historia 4',            'Historia'),
    (v_treyes_id,  85, 'Historia 5',            'Historia'),
    (v_treyes_id,  86, 'Historia 6',            'Historia'),
    (v_treyes_id,  87, 'Historia 7',            'Historia'),
    (v_treyes_id,  88, 'Historia 8',            'Historia'),
    (v_treyes_id,  89, 'Historia 9',            'Historia'),
    (v_treyes_id,  90, 'Historia 10',           'Historia'),
    (v_treyes_id,  91, 'Historia 11',           'Historia'),
    (v_treyes_id,  92, 'Historia 12',           'Historia'),
    (v_treyes_id,  93, 'Historia 13',           'Historia'),
    (v_treyes_id,  94, 'Historia 14',           'Historia'),
    (v_treyes_id,  95, 'Historia 15',           'Historia'),
    (v_treyes_id,  96, 'Trofeos 1',             'Trofeos'),
    (v_treyes_id,  97, 'Trofeos 2',             'Trofeos'),
    (v_treyes_id,  98, 'Trofeos 3',             'Trofeos'),
    (v_treyes_id,  99, 'Trofeos 4',             'Trofeos'),
    (v_treyes_id, 100, 'Trofeos 5',             'Trofeos'),
    (v_treyes_id, 101, 'Trofeos 6',             'Trofeos'),
    (v_treyes_id, 102, 'Trofeos 7',             'Trofeos'),
    (v_treyes_id, 103, 'Trofeos 8',             'Trofeos'),
    (v_treyes_id, 104, 'Trofeos 9',             'Trofeos'),
    (v_treyes_id, 105, 'Trofeos 10',            'Trofeos'),
    (v_treyes_id, 106, 'Trofeos 11',            'Trofeos'),
    (v_treyes_id, 107, 'Trofeos 12',            'Trofeos'),
    (v_treyes_id, 108, 'Trofeos 13',            'Trofeos'),
    (v_treyes_id, 109, 'Trofeos 14',            'Trofeos'),
    (v_treyes_id, 110, 'Trofeos 15',            'Trofeos'),
    (v_treyes_id, 111, 'Estadios Locales 1',    'Estadios Locales'),
    (v_treyes_id, 112, 'Estadios Locales 2',    'Estadios Locales'),
    (v_treyes_id, 113, 'Estadios Locales 3',    'Estadios Locales'),
    (v_treyes_id, 114, 'Estadios Locales 4',    'Estadios Locales'),
    (v_treyes_id, 115, 'Estadios Locales 5',    'Estadios Locales'),
    (v_treyes_id, 116, 'Estadios Locales 6',    'Estadios Locales'),
    (v_treyes_id, 117, 'Estadios Locales 7',    'Estadios Locales'),
    (v_treyes_id, 118, 'Estadios Locales 8',    'Estadios Locales'),
    (v_treyes_id, 119, 'Estadios Locales 9',    'Estadios Locales'),
    (v_treyes_id, 120, 'Estadios Locales 10',   'Estadios Locales'),
    (v_treyes_id, 121, 'Estadios Locales 11',   'Estadios Locales'),
    (v_treyes_id, 122, 'Estadios Locales 12',   'Estadios Locales'),
    (v_treyes_id, 123, 'Estadios Locales 13',   'Estadios Locales'),
    (v_treyes_id, 124, 'Estadios Locales 14',   'Estadios Locales'),
    (v_treyes_id, 125, 'Estadios Locales 15',   'Estadios Locales'),
    (v_treyes_id, 126, 'Figuras Historicas 1',  'Figuras Historicas'),
    (v_treyes_id, 127, 'Figuras Historicas 2',  'Figuras Historicas'),
    (v_treyes_id, 128, 'Figuras Historicas 3',  'Figuras Historicas'),
    (v_treyes_id, 129, 'Figuras Historicas 4',  'Figuras Historicas'),
    (v_treyes_id, 130, 'Figuras Historicas 5',  'Figuras Historicas'),
    (v_treyes_id, 131, 'Figuras Historicas 6',  'Figuras Historicas'),
    (v_treyes_id, 132, 'Figuras Historicas 7',  'Figuras Historicas'),
    (v_treyes_id, 133, 'Figuras Historicas 8',  'Figuras Historicas'),
    (v_treyes_id, 134, 'Figuras Historicas 9',  'Figuras Historicas'),
    (v_treyes_id, 135, 'Figuras Historicas 10', 'Figuras Historicas'),
    (v_treyes_id, 136, 'Figuras Historicas 11', 'Figuras Historicas'),
    (v_treyes_id, 137, 'Figuras Historicas 12', 'Figuras Historicas'),
    (v_treyes_id, 138, 'Figuras Historicas 13', 'Figuras Historicas'),
    (v_treyes_id, 139, 'Figuras Historicas 14', 'Figuras Historicas'),
    (v_treyes_id, 140, 'Figuras Historicas 15', 'Figuras Historicas'),
    (v_treyes_id, 141, 'Especiales 1',          'Especiales'),
    (v_treyes_id, 142, 'Especiales 2',          'Especiales'),
    (v_treyes_id, 143, 'Especiales 3',          'Especiales'),
    (v_treyes_id, 144, 'Especiales 4',          'Especiales'),
    (v_treyes_id, 145, 'Especiales 5',          'Especiales'),
    (v_treyes_id, 146, 'Especiales 6',          'Especiales'),
    (v_treyes_id, 147, 'Especiales 7',          'Especiales'),
    (v_treyes_id, 148, 'Especiales 8',          'Especiales'),
    (v_treyes_id, 149, 'Especiales 9',          'Especiales'),
    (v_treyes_id, 150, 'Especiales 10',         'Especiales')
  on conflict (album_id, number) do nothing;

end;
$$;
